name: Run Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs the job daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas yfinance prophet hsfs joblib scikit-learn

    - name: Run pipeline
      run: |
        python pipeline.py
